### ISSUE TITLE
[Validation] Create report of validation problems

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon-issue-tracking-system#229]
```
[AA:] Validation of multiple projects should probably generate a compact 
"report" as a summary of all validation results and display this on the console
```

Original issue reported on code.google.com by `roland.k...@googlemail.com` on 21 Oct 2014 at 9:11

**Comment by RolandKluge** [comment]
Is this issue resolved now?

**Comment by gkulcsar** [comment]
I'm not sure, gonna check next week. Something (at least the possibility of multi-validation) has been implemented during the last Hacker Days, but I don't know if it is satisfactory or is what was meant when posting the issue.
