### ISSUE TITLE
[TGG] Do not Generate all isAppropriate Methods for Batch TGGs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon-issue-tracking-system#236]
```

We only need one entry method (isappropriate) in case of batch transformation.

This would especially decrease the code generation time in huge TGGs 
```

Original issue reported on code.google.com by `erhanleb...@hotmail.com` on 21 Oct 2014 at 2:28

**Comment by erhanleblebici** [comment]
I won't optimize the existing implementation in the proposed manner but think about a more radical change by eliminating isAppropriate-Methods
