### ISSUE TITLE
[eMoflon][License] Which License has eMoflon?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon-issue-tracking-system#247]
```
Project Site is EPL
Handbook is GPL3
Eclipse Plugin is LGPL
EA Addin is CPL


```

Original issue reported on code.google.com by `zniper1...@googlemail.com` on 24 Oct 2014 at 2:42

**Comment by RolandKluge** [comment]
Decision:
 - documentation: GNU Free Documentation License (https://gnu.org/licenses/fdl.html)
 - eMoflon: GNU General Public License
