### ISSUE TITLE
[Validation] Outgoing edge of start node should have guard NONE

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon-issue-tracking-system#252]
```
(see title)
```

Original issue reported on code.google.com by `roland.k...@googlemail.com` on 3 Nov 2014 at 11:53

**Comment by gervarro** [comment]
Issue fixed by commit #1266 in the Validation.eap. This new functionality has not been tested as EA already reports the same error, and the textual syntax could not be used on May 21st, 2015.
