### ISSUE TITLE
[Moflon] "Headless" Moflon

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon-issue-tracking-system#271]
```
Define a process how to produce a stand-alone software that uses eMoflon.
```

Original issue reported on code.google.com by `roland.k...@googlemail.com` on 14 Nov 2014 at 11:02

**Comment by RolandKluge** [comment]
I guess, it would already help to document how to create a runnable Jar file in the handbook.

**Comment by RolandKluge** [comment]
Done.
