### ISSUE TITLE
[EA] Issue with export of tagged values

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon-issue-tracking-system#303]
```
Seems iff Moflon::Export := false; changes in Tagged values are not propagated 
to ExportTree


```

Original issue reported on code.google.com by `f.deckwe...@googlemail.com` on 23 Dec 2014 at 1:30

**Comment by SchleichAlex** [comment]
they are only propagated to the saved moca tree in ea if you update the package (doubleclick and ok)
but changed tagged values are recognized correctly during the export.
