### ISSUE TITLE
Provide dot.exe with Plugin 

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#362]
Currently we require the user to have I stalled dot (for our visualization to work).

Some users find this so much work that they simply do not use the visualisation because of this ;)

Why don't we provide a dot.exe with our plugin so we can produce visualisations out of the box.  This would also simplify the code (no check and error handling).

I would only support windows for the moment (Mac/Linux on demand).

**Comment by RolandKluge** [comment]
Done.
