### ISSUE TITLE
Validate workspace Misc

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#368]
1.	SDMTestSuite::BooleanStatementNodes [?]
2.	DemoLanguages::DictionaryCodeAdapter [?]
3.	DemoLanguages::DoubleLinkedListLanguage [Greg: interessanter Kompilierfehler!]
4.	Mosopolite::FlatteningRules [?]
5.	LSCtoMPN::LSCToMPNTransformation [?]
6.	Mosopolite::mCSPSubsetExtraction [?]
7.	DemoLanguages::MemoryBoxLanguage [?]
8.	MocaToMoflonAttributeConstr::MocaToMoflonAttributeConstrTestGenerator [Fred]
9.	LSCtoMPN::MPNToMPNGenViewTransformation [?]
10.	SDMTestSuite::OptionalLinkCreateDelete [?]
11.	CDDS::SimpleClass2RDBMS  [?]

**Comment by anthonyanjorin** [comment]
I have now removed all mosopolite and LSC/MPN projects as well as other projects that do not make sense any longer (e.g., testing the handling of optional links).

I have also switched to Democles in all projects and updated the relevant PSF.

The work remaining is now to get all projects to validate for Democles.
