### ISSUE TITLE
Remove export of org.apache.log4j packages

### ISSUE THREAD

**Issue by skorsky** [eMoflon/emoflon-issue-tracking-system#374]
The plug-ins org.moflon.dependencies and org.moflon.moca export packages of org.apache.log4j. This is in version 1.0.0.201502020906 and others.

Please remove these exports! This is blocking other plug-ins from integrating eMoflon.

Instead use import-package with the appropriate version constraint. p2 is able to install the org.apache.log4j bundle from other update sites if these are enabled.

Currently I get the following error log entry, which describes a 'Uses constraint violation':
eclipse.buildId=unknown
java.version=1.8.0_40
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data ../runtime-Eclipse -dev file:./.metadata/.plugins/org.eclipse.pde.core/Launch Runtime Eclipse/dev.properties -os win32 -ws win32 -arch x86_64

com.softwareag.research.heads.ceprecommender
Error
Thu Mar 26 16:53:20 CET 2015
FrameworkEvent ERROR

org.osgi.framework.BundleException: Could not resolve module: com.softwareag.research.heads.ceprecommender [1462]
  Bundle was not resolved because of a uses contraint violation.
  org.osgi.service.resolver.ResolutionException: Uses constraint violation. Unable to resolve resource com.softwareag.research.heads.ceprecommender [osgi.identity; osgi.identity="com.softwareag.research.heads.ceprecommender"; type="osgi.bundle"; version:Version="1.0.0.qualifier"; singleton:="true"] because it is exposed to package 'org.apache.log4j' from resources org.moflon.moca [osgi.identity; osgi.identity="org.moflon.moca"; type="osgi.bundle"; version:Version="1.0.0.201409161440"; singleton:="true"] and org.apache.log4j [osgi.identity; osgi.identity="org.apache.log4j"; type="osgi.bundle"; version:Version="1.2.15.v201012070815"] via two dependency chains.

Chain 1:
  com.softwareag.research.heads.ceprecommender [osgi.identity; osgi.identity="com.softwareag.research.heads.ceprecommender"; type="osgi.bundle"; version:Version="1.0.0.qualifier"; singleton:="true"]
    require: (osgi.wiring.bundle=org.moflon.moca)
     |
    provide: osgi.wiring.bundle: org.moflon.moca
  org.moflon.moca [osgi.identity; osgi.identity="org.moflon.moca"; type="osgi.bundle"; version:Version="1.0.0.201409161440"; singleton:="true"]

Chain 2:
  com.softwareag.research.heads.ceprecommender [osgi.identity; osgi.identity="com.softwareag.research.heads.ceprecommender"; type="osgi.bundle"; version:Version="1.0.0.qualifier"; singleton:="true"]
    require: (osgi.wiring.bundle=org.apama.epl)
     |
    provide: osgi.wiring.bundle; bundle-version:Version="1.0.0.qualifier"; osgi.wiring.bundle="org.apama.epl"; singleton:="true"
  org.eclipse.xtext.util [osgi.identity; osgi.identity="org.eclipse.xtext.util"; type="osgi.bundle"; version:Version="2.8.1.v201503230617"]
    import: (&(osgi.wiring.package=org.apache.log4j)(version>=1.2.15))
     |
    export: osgi.wiring.package: org.apache.log4j
  org.apache.log4j [osgi.identity; osgi.identity="org.apache.log4j"; type="osgi.bundle"; version:Version="1.2.15.v201012070815"]
	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

**Comment by RolandKluge** [comment]
Thank you for your report and sorry for the late response.

We are working on that issue and hope to be able to fix it in the next release.

**Comment by skorsky** [comment]
Thanks for response.
If there are questions regarding OSGi bundle manifests, I can help.

**Comment by RolandKluge** [comment]
The issue should now be fixed in the current beta of eMoflon, available at: http://www.moflon.org/fileadmin/download/moflon-ide/eclipse-plugin/beta/update-site2/

Please do not hesitate to report if your problem persists.

**Comment by RolandKluge** [comment]
I close this issue for now.
