### ISSUE TITLE
Validation problem with deleting bound variables

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#377]
See attachment for problematic case.

In the diagram, a validation error is produced for the storynode [delete constraint ( lessThan, lessThanEq,  etc. can't be converted )], although this is actually ok.

The error is:  "A deleted bound variable as already been deleted earlier".
![problematiccase](https://cloud.githubusercontent.com/assets/6302793/6869131/ef03ffac-d491-11e4-9fc2-58a9422f0be0.PNG)

**Comment by gervarro** [comment]
Fixed by commit #1214 in the Validation project. A reinitialization in a nested loop was missing.
