### ISSUE TITLE
Validation problem with bound and deleted loop variable

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#378]
A validation error "bound variable has already been deleted earlier" is produced for a case where a loop variable is deleted in the loop context (see attachment).  

In the example, the variable lv is deleted in [delete negative lv] and [delete if create].  The validation error is issued for [change to context] although this is not problematic (lv is overwriten everytime the loop is repeated).

![problematiccase](https://cloud.githubusercontent.com/assets/6302793/6869390/dfbea31a-d493-11e4-9794-f9d722707b9c.PNG)

**Comment by gervarro** [comment]
Fixed by commit #1214 in the Validation project. A reinitialization in a nested loop was missing.
