### ISSUE TITLE
Validation problems with StopNodes in ForEach-Components

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#379]
StopNodes in ForEach-components can be considered as "bad style" but should be flagged as warning and not errors.  We have discussed this already a few times and in some cases, doing things "right" involves a lot of NACs and flags etc.  A ForEach with a StopNode is sometimes much easier...

**Comment by gervarro** [comment]
Although I would prefer a configurable solution to this problem in a long-run, in which the default severity is error, I now lowered the default severity to warning to avoid blocking the move to Democles.
