### ISSUE TITLE
Incomplete list of variables when specifying attribute value expressions (missing method parameters)

### ISSUE THREAD

**Issue by gervarro** [eMoflon/emoflon-issue-tracking-system#380]
When an attribute value expression is aimed to be defined (as an attribute constraint or a binding on an object variable), the enumerated objects do not contain the parameters of the method, although the attributes of the method parameters should definitely be available in the whole method.

**Comment by SchleichAlex** [comment]
the sdm metamodel in it's current state does not allow EParameters as targets for AttributeValueExpressions. An easy solution would be to bind the parameter as an object variable in the sdm.
