### ISSUE TITLE
Consolidate our two "modi" for Democles validation

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#384]
At the moment, we seem to have two modi for Democles validation:  (1) when generating code, and (2) when the user explicitly invokes eMoflon/Validate.

I'm not sure why the behaviour is different, but I think a user expects (1) to behave exactly as (2), e.g., to also create problem markers.

**Comment by gkulcsar** [comment]
Done.
