### ISSUE TITLE
[EA Validation Rule] Forbid character " in names of activity nodes (validation rule in EA)

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#385]
We need a new validation rule in EA to forbid " as a character in names of activity nodes.

These strings are used as comments in our generated code and are enclosed with "...".

**Comment by RolandKluge** [comment]
I restricted the domain of activity node names to the following regex: @"^[\sa-zA-Z_-][\sa-zA-Z0-9_-]*$"
