### ISSUE TITLE
Move TGGRuntime, TGGLanguage, and CSPCodeAdapter (+ SDMLanguage) to a separate meta-model

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#399]
For modularizing eMoflon, it is definitely sensible to separate the TGG-related and probably the SDM-related stuff from the other contents of core languages.

**Comment by erhanleblebici** [comment]
done for TGGs. SDMLanguage is still part of CoreLanguages. If any further separation for SDMs is planned (see brackets in the title), another issue must be opened.
