### ISSUE TITLE
[Validation] Improve error messages if Democles code generation fails

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#408]
If generating code with Democles fails, the error messages often do not contain immediate evidence why this happened.

For instance, the code generation may stop with the error message "Unbound variable is specified as bound", but does not provide evidence which variable is meant actually.

The current workaround is to manually trigger the validation whose error messages are mostly very helpful.

**Comment by gkulcsar** [comment]
Code generation now has the same validation procedure as manual validation.
