### ISSUE TITLE
Non-compilable TGG code 

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#431]
In SokobanImportExport, the following non-compilable code is generated in class EOperationTableBridgeImpl:

    public RuleResult checkAttributes_FWD(TripleMatch tripleMatch) {
    // ...
		if (null == 3) {
			ruleResult.setSuccess(true);
		} else {
			ruleResult.setSuccess(false);
		}

		return ruleResult;
	}

Similar problems can be observed for the FixML projects.

**Comment by RolandKluge** [comment]
The problem arises from the template Csp.stg and is located in *TGGLanguage.compiler.compilerfacade.impl.InjectionHelperImpl#handleAttributeAssignmentsAndConstraints*.

**Comment by RolandKluge** [comment]
@anthonyanjorin This may be also interesting for you (BTW: This is how you can CC people) :-)

**Comment by anthonyanjorin** [comment]
A quick fix might be to swap the order of the parameters of the comparison operator.

So using "Yoda" style:  if(3 == null)

I don't understand what is null and how that can happen, but if Yoda style solves the problem for the moment then this can be done in a few seconds by changing Csp.stg

**Comment by RolandKluge** [comment]
Ok, I try that.

**Comment by anthonyanjorin** [comment]
Ok so the nulls really don't make sense.  This has to be fixed then.

**Comment by RolandKluge** [comment]
Has this been fixed so far?

**Comment by anthonyanjorin** [comment]
It's been deactivated and postponed till after the current Master thesis (then we can hopefully fix this and write some tests)

**Comment by erhanleblebici** [comment]
master thesis is finalized and templeate problems are fixed
