### ISSUE TITLE
Describe additional eMoflon features on the website

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#434]
There exists a number of topics/features that should be - according to the features requests in the issue tracker - described in the handbook.
I suspect that several of these topics will end up in Part 6 because they do not fit into the storyline of the handbook.

Therefore, I suggest to "additional"/isolated topics on the website www.emoflon.org in a blog-like manner.

What do you think, @anthonyanjorin @erhanleblebici @gervarro ?

**Comment by anthonyanjorin** [comment]
As the rest of the handbook is already in latex/pdf I'm not sure it's a good idea to start a new format and location for a new part.  And working directly on www.emoflon.org is not necessarily easier...

**Comment by RolandKluge** [comment]
That's right. I am still searching for a way how to "publish" news for eMoflon apart from the Changelog.

I am closing this for now.
