### ISSUE TITLE
Better error messages of RuntimeExceptions in generated code

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#436]
Error messages in the generated code should contain more information. One possibility would be to print the variable and the pattern names.

Current example: 

    public EReference getEReference(LinkVariable linkVariable)
    {
    // LookupEReference
      Object[] result1_black = PatternTransformerImpl.pattern_PatternTransformer_1_1_blackBFFF(linkVariable);
      if (result1_black == null)
      {
         throw new RuntimeException("Pattern matching in node [LookupEReference] failed");
      }
    }

Expected: 

    Object[] result1_black = PatternTransformerImpl.pattern_PatternTransformer_1_1_blackBFFF(linkVariable);
    if (result1_black == null)
    {
         throw new RuntimeException("Pattern matching in node [LookupEReference] failed. Variables: [linkVariable] = " + linkVariable + ".");
    }

**Comment by gervarro** [comment]
Issue fixed by commit #3971
