### ISSUE TITLE
SynchronizationHelper constructor should accept a ResourceSet as input parameter

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#438]
Currently, the SynchronizationHelper instantiates its own resource set. In some cases the user may want to provide a custom resource set. 

I have already added a single-argument constructor. It remains to be checked whether this has any negative implications.

(Initiated by @gervarro  and Sven)

**Comment by erhanleblebici** [comment]
done. please check the new SynchronizationHelper
