### ISSUE TITLE
Hitting the "build" button for metamodel projects now invokes the repository builder

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#443]
Shouldn't our build button should actually just call the normal "build" function in Eclipse?
In this way all builders of the project get invoked in the right order...

Currently a fix now explicitly invokes the RepositoryBuilder regardless of what the project is or has as builders.  This leads to strange behaviour for MetamodelProjects.  Especially for MOSL, it is now impossible to invoke the parsers and the MOSL transformation with the button (the RepositoryBuilder is invoked and complains that /model is missing).

I'm not sure how to consolidate this as I don't understand why this was "fixed" in the first place.  In any case, a solution should be found for MetamodelProjects.

**Comment by RolandKluge** [comment]
The problem with the generic call to IProject#build() was that projects with large Antlr files take a very long time for cleaning and building (e.g., MOSLCodeAdapter) even though we actually only want to clean the generated code.

I reverted the change and will investigate how to improve this performance issues at some time in the future.
