### ISSUE TITLE
Please document why methods are deprecated

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#444]
It would be very helpful to document briefly why deprecated methods are marked as such and what should be used instead.  Users can then easily change their code accordingly.

**Comment by gervarro** [comment]
I added comments to the deprecated methods.

External users should be able to configure their own resource sets (see experience from the TTC 2015). In general, I would like to enforce the explicit creation (and the possible reuse) of resource sets. It is a bad style to implicitly create a new resource set in a helper method, whenever a resource is saved. The suggested solution is to create a single resource set (createDefaultResourceSet()) for a whole session, create/load/save resources with the standard methods (ResourceSet.createResource(URI), ResourceSet.getResource(URI, true), Resource.save(null)).

Tailored EPackages can be registered in standalone Java programs by accessing the eINSTANCE static attribute. In other cases, the EPackage can be registered in the package registry of a resource set (ResourceSet.getPackageRegistry()) programmatically or automatically with the plugin.xml mechanism.

Cross-reference adapters have to be installed only once on a resource set (but not for all contained resources) (installCrossReferencers(ResourceSet)).
