### ISSUE TITLE
[EA] Validation rule for TGG CSPs has problems with negative numbers as literal expressions

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#453]
Validating CME.eap (Zoo1, Siemens project) now results in several validation errors.

It seems that negative numbers, e.g., -1 are now flagged as invalid literal expressions in TGG CSPs.

@RolandKluge : Is this due to a new change?  Or is this desired behaviour for some reason?

**Comment by RolandKluge** [comment]
Was a bug, indeed. Fixed now.
