### ISSUE TITLE
Revisit temporary solution for bug in SychronizationHelper

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#456]
The SynchronziationHelper had a serious problem because the mapping of "targetModel" to the URI of the final output file (e.g., fwd.trg.xmi) was removed after using it in "saveTrg". This caused the call to "saveCorr" to lack the correct URI mapping and so the href in (e.g.) "fwd.corr.xmi" was something like "./targetModel" instead of "./instances/fwd.trg.xmi".

The problem was resolved by manually registering the appropriate URI mappings before calling eMoflonEMFUtil#saveModel.

This solution should be revisited. Maybe it is a good idea to inline the logic for saving models in the SynchronizationHelper.

**Comment by erhanleblebici** [comment]
we now use the new save methods for an appropriate handling of URI mappings
