### ISSUE TITLE
Handbook example in eMoflon test suite

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#461]
We should check whether the current handbook example is currently completely part of the eMoflon test suite.

**Comment by anthonyanjorin** [comment]
So it certainly is not, unfortunately.

We should also think of some way to ensure that the "version" in the testsuite is always the same as in the handbook cheat wizards...

JUnit Tests are also missing :(

@erhanleblebici

**Comment by RolandKluge** [comment]
One way to ensure this would be to not "statically" package the cheat projects but to provide them via SVN. This would, however, require users to be online when checking out the cheat projects -- I guess this is a sensible assumption.

**Comment by anthonyanjorin** [comment]
how about updating the wizards everytime we deploy (release)?  But yes treating the cheat projects just like our other (test) workspaces is also fine for me.

**Comment by anthonyanjorin** [comment]
The latest idea is to consolidate all our Demo, Handbook Cheat Wizards, and normal Workspaces by using the exact same infrastructure.  @RolandKluge

**Comment by RolandKluge** [comment]
The handbook examples are now all in the eMoflon test suite repository.
I have created a PSF file for each wizard.

We should now think about getting rid of the wizards. People should simply use the PSF files to get the cheat solution. We have to think about how to give people access to the tests repository.

**Comment by anthonyanjorin** [comment]
any ideas on how we can allow anyone to check out some of our repositories?

@RolandKluge you mentioned something about a standard user and passwort combi?  Do we have this already?  If yes then I could/should test using it and we could give these credentials in the handbook.

Does that make sense?

**Comment by RolandKluge** [comment]
Yes, readonly access to the repositories seems to be possible. We would have to publish the password or provide password-less access. However, a password-less access could impose security risks. Perhaps we could even have a separate repository for the handbook examples on GitHub, for instance?

**Comment by anthonyanjorin** [comment]
Would make sense...  Hopefully our PSF-based mechanism works with GitHub.  It seems to support Subversion clients: https://help.github.com/articles/support-for-subversion-clients/

**Comment by anthonyanjorin** [comment]
I'll also handle our "Demo" suite (which we plan to extend in the future) in this manner.
