### ISSUE TITLE
Remove fixed path assumption from TransformationTest

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#468]
Currently, the constructor of TransformationTest assumes that the correspondence project (e.g. ABCIntegration) is located at "../ABCIntegration", which is a dangerous assumption because the workspace structure may not be mirrored in the file system.

We should find a way to address the correspondence project via its project name.

The problematic constructor looks like this:
public TransformationTest(EPackage sourcePackage, EPackage corrPackage, EPackage targetPackage)
   {
      this.integrationName = corrPackage.getName();
      this.sourcePackage = sourcePackage;
      this.corrPackage = corrPackage;
      this.targetPackage = targetPackage;
      helper = new SynchronizationHelper(corrPackage, "../" + corrPackage.getName());
   }

@anthonyanjorin @erhanleblebici

**Comment by erhanleblebici** [comment]
If the situation described above occurs (which is not in line with our current tests anyway), the user has to consider to write a subclass of TransformationTest and set its paths on its own (all fields of the TransformationTest are protected)
