### ISSUE TITLE
ANT cannot find org.moflon.core.utilities on exporting TGG plugins

### ISSUE THREAD

**Issue by mabilov** [eMoflon/emoflon-issue-tracking-system#470]
When I am trying to export my TGG project as deployable plugins, ant gives me an error that it cannot find org.moflon.core.utilities plugin, My guess is that it happens because this plugin is installed as a directory in the plugins folder and ant cannot load it properly. 

And the project builds in the eclipse workspace without errors. 

150. ERROR in C:\Users\marat\Documents\EclipseWS\Luna\moflon\BpmnToUseCaseIntegration\gen\BpmnToUseCaseIntegration\Rules\impl\CatchEventAfterEBGToStepRuleImpl.java (at line 4332)
	for (ProcessToUseCase processToUseCase : org.moflon.core.utilities.eMoflonEMFUtil
	                                         ^^^^^^^^^^^^^^^
org.moflon.core cannot be resolved

Export of the plugin is required because I need to execute my plugins in the OSGI environment. That is because org.moflon.core.utilities imports third-party antlr library which somehow replaces XText ANTLR, and gives always error on Token.EOF.

**Comment by RolandKluge** [comment]
This is a known problem that also annoyed us several times in the past. We will check how to fix this issue. Currently, unpacking *org.moflon.utilities* is necessary for technical reasons.

**Comment by RolandKluge** [comment]
The problem are indeed the Antlr libraries are shipped with the org.moflon.core.utilities bundle. We should move them into separate bundles and disable the "unpack" option.

**Comment by RolandKluge** [comment]
The problem should be fixed now. Please update your version of eMoflon using the beta update site: http://www.moflon.org/fileadmin/download/moflon-ide/eclipse-plugin/beta/update-site2/

**Comment by mabilov** [comment]
Thank you, Now I can export my plugins without problem
