### ISSUE TITLE
Improve TGG rule loading in SynchronizationHelper

### ISSUE THREAD

**Issue by SvenPeldszus** [eMoflon/emoflon-issue-tracking-system#471]
Currently the constructor of ```SynchronizationHelper``` has a parameter for the path to the TGG project. This path is only used for loading the TGGRules. The current loading mechanism  is very inflexible for a integration into many project kinds.

Please provide a constructor for ```SynchronizationHelper```, which only has the TGGPackage ```final EPackage corrPackage``` as parameter or even no parameter. For the other values (```ResourceSet``` and TGGRules ```*.sma.xmi```) only provide public setter methods.

For the TGGRules please provide a setter which takes the ```*.sma.xmi``` file directly as ```InputStream```. With the usage of an ```InputStream``` it does not matter whether the ```*.sma.xmi`` file is located on any place in the file system or inside a jar file.

```org.eclipse.emf.ecore.resource.Resource``` already provide all functionalities to load models from InputStreams.

All in all this could look like the following.
```
boolean init(ResourceSet rs, InputStream tgg_rules){
  if(rs!=null){
    setResourceSet(rs);
    Resource r = rs.getResource("TGGRules.sma.xmi", true);
             r.load(tgg_rules, Collections.EMPTY_MAP);
   for(EObject e : r.getContents()) {
     if(e instance of StaticAnalysis){
          setRules((StaticAnalysis) e);
          return true;
      }
    }
    return false;
  }
  return false;
}
```

Currently the ```private void loadRulesFromProject(final String, final String)``` method uses the deprecated method ```eMoflonEMFUtil.loadModelWithDependencies(String, ResourceSet)```. This had already been changed in a previous version.

**Comment by erhanleblebici** [comment]
you should consider to implement your own subclass of SynchronizationHelper and set its fields by yourself. (all fields are protected such that you can access them from your own special implementation)

**Comment by SvenPeldszus** [comment]
Implementing a subclass of ```SynchronizationHelper``` for this purpose is not possible. The constructor of such a subclass has to call a constructor of the superclass. As all constructors provided in ```SynchronizationHelper``` require the path to the TGG project as parameter (and try to load the rules from this project at initialization) you force one to use your method of loading rules. If e.g. no valid path to the TGG project is available, e.g. as I want to load the rules from a jar, file a ```IllegalArgumentException``` is thrown and catched somewhere deep inside of eclipse.

**Comment by erhanleblebici** [comment]
Would a protected default constructor (which does nothing) solve your problem, at least when you write your own subclass?

**Comment by SvenPeldszus** [comment]
Yes, in this case , I can handle everything in the subclass.

**Comment by erhanleblebici** [comment]
added default constructor so that you can subclass it
