### ISSUE TITLE
eMoflon Version Numbering

### ISSUE THREAD

**Issue by SvenPeldszus** [eMoflon/emoflon-issue-tracking-system#473]
Currently the eclipse Plugin of eMoflon has a continuous version number, which is increased with each release.

The version number of the EA Plugin is only increased for major releases.
Currently it is version 1.7.0 in EA at EXTENSIONS -> MOFLON::Ecore::Addin -> About... . In the Windows program manager it is always version 1.0.0.0.

As even between the major releases functionality changes it is hard to determine whether different eMoflon installations are compatible and to detect outdated eMoflon installations. Therefore the version number of the EA Addin should be increased with every release, too.

Additionally for both plugins the version number should be displayed beside the download links on the eMoflon website.

**Comment by RolandKluge** [comment]
"Solved" now:
- The msi file contains the current version (e.g., EAEcoreAddin-x86-1.7.0.0-b2015_06_23__140323.msi)
- The version that is shown in "Programs and Features" may only contain integers (0-65535) when building the installer using Wix. The build date does not really fit into this variable. Still, we will do our best to keep this version in sync with the eMoflon version.
