### ISSUE TITLE
Check Attributes Fwd

### ISSUE THREAD

**Issue by mabilov** [eMoflon/emoflon-issue-tracking-system#475]
TGG rule code in methods: checkAttributes_FWD and checkAttributes_BWD throws UnsupportedOperationException. Would it be possible to replace it with some dummy code, so the transformation will end with some warnings?
Something like this would suffice:

RuleResult res = TGGRuntime.TGGRuntimeFactory.eINSTANCE.createRuleResult();
res.setSuccess(true);
return res;

**Comment by RolandKluge** [comment]
@erhanleblebici @anthonyanjorin

**Comment by anthonyanjorin** [comment]
@mabilov  Could you try out our latest beta to see if the problem persists?  We have fixed a lot of bugs related to attribute deltas recently (propagating attribute changes should now work).

**Comment by anthonyanjorin** [comment]
I guess this is resolved.  If not please reopen.
