### ISSUE TITLE
[TGG Debug] Show rule names of Input Matches directly

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-issue-tracking-system#476]
In the TGG debug view, it is hard to distinguish between input matches at a first glance as all of them are shown as "TGGRuntime.Match". The user has to navigate to the ruleName of each Match.

Could we use ruleName as the uppermost identifier of Matches? Then you can actually remove the ruleName feature. Please check the screenshot for details.

![screenshot 2015-06-25 11 24 36](https://cloud.githubusercontent.com/assets/11506522/8351462/c0e13d46-1b2d-11e5-9a45-82525402dd27.png)

**Comment by mballhausen** [comment]
The Input Matches have now a new visual presentation:

![match 20solution](https://cloud.githubusercontent.com/assets/11562573/8507631/c3a0c9d2-224b-11e5-8215-0723b9356716.png)

**Comment by mballhausen** [comment]
The rule name is now part of the "Input Match .."-title.
