### ISSUE TITLE
[TGG Debug] NPE when visualizing TripleMatches

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-issue-tracking-system#478]
check the screenshot to see the steps which caused an NPE:

![screenshot 2015-06-25 11 36 08](https://cloud.githubusercontent.com/assets/11506522/8351615/049bf43a-1b2f-11e5-89d5-1ee8fcfe55dc.png)

**Comment by mballhausen** [comment]
Could you provide a screenshot showing the content of Correspondence Elements?

**Comment by erhanleblebici** [comment]
Correspondence Elements do not seem to be broken. Aren't you able to reproduce the error by yourself?

![screenshot 2015-06-26 11 38 28](https://cloud.githubusercontent.com/assets/11506522/8374731/28ede0e0-1bf8-11e5-8ef4-eeaba1926192.png)

**Comment by erhanleblebici** [comment]
I think the problem might be cause due to EMoflonEdges having source and target as NULL (see the screenshot below)
![screenshot 2015-06-29 09 50 52](https://cloud.githubusercontent.com/assets/11506522/8403399/954a2fd4-1e44-11e5-9b95-5bcb1d0281bc.png)

**Comment by mballhausen** [comment]
A fix is commited. The triple match is partly empty during the translation. Now, "null" values are handled appropriately.

**Comment by mballhausen** [comment]
.

**Comment by erhanleblebici** [comment]
I verify that NPE is solved but null handling is just a workaround.

I close this one and open a related issue because I can now describe the problem from a different point of view and not via NPEs
