### ISSUE TITLE
[TGG Debug] Automatize Debug Model after each changes in Synchronizer.java and SynchronizationHelper.java

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-issue-tracking-system#481]
org.moflon.ide.debug.annotation.processor should be invoked automatically when Synchronizer.java and SynchronizationHelper.java are changed

Some hints for the development:
1) Implement a new builder in the project org.moflon.ide.debug.annotation.processo
2) register this builder for TGGLanguage. You can only test it if you start another workspace from your Eclipse and check out the whole developer workspace again
3) Please also consider the robustness of this builder. That is, errors must be shown in the console in case of any Exception (due to missing jdk or wrong paths) but the regular Java/Eclipse build process should not suffer from these exceptions. 

4) You might also consider to show a warning which says that the user must commit the debug.init.xmi as it is changed.

**Comment by mballhausen** [comment]
The builder is now implemented and therefore the package org.moflon.ide.debug.annotation.processor became part of the moflon ide feature. From now on a JDK must be configured as your JAVA_HOME system variable. The screenshots below illustrate the behavior of the builder.

Please verify the work of the builder.

![changebefore](https://cloud.githubusercontent.com/assets/11562573/8767347/db134f62-2e59-11e5-8c4a-273b4eab1158.png)
![changeafter](https://cloud.githubusercontent.com/assets/11562573/8767346/db0f32ec-2e59-11e5-9e20-d40d27b1708a.png)

**Comment by mballhausen** [comment]
Update: When installing a new workspace, the builder starts before all projects are build completely and thereby errors are reported. If all projects are build completely the builder works as expected. Do you know how to disable/reorder the builder that he will just be triggered when a full build is complete? Could you handle this?
Regards

**Comment by anthonyanjorin** [comment]
Hi Marco,  have you tried ordering the builders for the TGGLanguage project?  Their order in the .project file is really important.  Why is it important that other projects have not been built yet?  Only the single TGGLanguage project is relevant right?

**Comment by mballhausen** [comment]
Hi Tony, this is a good point I'll try that. The issue is a matter of the build execution order. The tool compiles the Synchronizer and SynchronizationHelper and thus has dependencies on other projects (org.moflon.core.utilities, TGGLanguage,TGGRuntime, and some emf packages). When a new developer workspace is checked out all project are compiled. If the builder is called before the depended packages are compiled there will be an error. The interesting part is that even an error is thrown this does not influence the correct workspace build. Actually, the builder is called at the end of the process again and succeeds. 

So changing the order might already fix the issue. Another try could be to disable the builder on a full build. In other situations he's working. The builder will start working if you deploy a new eMoflon.

**Comment by anthonyanjorin** [comment]
I discussed this with Erhan today and we were wondering if one could set the break points in a basis class in the inheritance hierarchy (this has to be decided carefully) with a dummy "stop" method.

We would never change this class.

All the synchroniser classes we work on all the time would just call this dummy method whenever one wants to stop and hold in the debugger.

Would this work?  If yes then this is much more light weight and simpler than a builder (needing JDK etc).

@erhanleblebici did I describe your idea correctly?

**Comment by mballhausen** [comment]
Update: I found a solution for the problem. I now check for build problems in TGGLanguage if they exists the builder is skipped. Only if all projects are compiled he is active.

Therefore, no build errors during workspace compilation otherwise tell me.

**Comment by mballhausen** [comment]
Can we handle the other approach as a separate feature request? 

Changing to subclasses requires rework of the debuggers JDI-communication which can have some pitfalls. I agree that such methods can improve readability. But introducing sub classing can increase the complexity for the end-user as the debugger classes occur at his side and might require to adapt the forward/backward synchronizer and I don't know what will be effected by such a change. For the new request: How about introducing such methods first (at a point in future) and generating debug.init.xmi with the now existing tooling to first check if the breakpoints will work correctly when wrapped in methods (such details are not clear at the moment). Afterwards introduce some sub classes test wise and checking the result. Finally the tooling can be reduced. But I guess someone who develops the debugger does not want to update code lines in any situation manually ;)

We had once the situation that a hierarchy change of the synchronizer was introduced (@erhanleblebici you remember?) and this caused some problems and was thus reverted. But of course let's discuss this in detail first :)
