### ISSUE TITLE
[TGG Debug] Find java home automatically 

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-issue-tracking-system#482]
In the tooling org.moflon.ide.debug.annotation.processor, which updates the debug model (debug.init.xmi), there are constant paths being used for java home. Please utilize existing environment variables to find out java path automatically.

to be adjusted: the method computeDebugAnnotations in the class DebugAnnotation

**Comment by mballhausen** [comment]
The DebugAnnotation.java is now adapted. The explicit set of a "java.home" is removed. Instead it is configured via a launch configuration property. In addition, an example launch configuration is checked in too. See the images below how to configure a JDK for your workspace and the DebugAnnotation launch configuration in case you use a different JDK.
 
![workspace_jdk](https://cloud.githubusercontent.com/assets/11562573/8615987/d2ab8cfe-26f7-11e5-841a-5cf0127ec750.png)
![launchconfig_jdk](https://cloud.githubusercontent.com/assets/11562573/8615988/d2b22fa0-26f7-11e5-90a5-6846e34f10c1.png)
