### ISSUE TITLE
[TGG] Improve FF generation for eq constraint

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#484]
At the moment the FF implementation for eq looks like this:
else if (bindingStates.equals("FF"))
````
 {
     String value = Generator.getNewRandomString(a.getType());
     a.bindToValue(value);
     b.bindToValue(value);
     setSatisfied(true);
}
````
This does not make sense as the values to be generated are not always of type String.  Better would be a simple check to see if the types are either: Strings, Numbers, Bools, or Enums and generate appropriate values.  This is not too complex and should work out fine (at the moment ClassCastExceptions are flying everywhere).

@SchleichAlex

**Comment by erhanleblebici** [comment]
provided a new method for value generation and implemented it for standard cases like String, Boolean, Integer etc. You can easily extend this method when you see a new unsupported type.
