### ISSUE TITLE
[TGG] TODOs and deprecated code

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#485]
We currently have TODOs and deprecated code in SynchronizationHelper.

These problems should be solved or removed soon or we'll forget what they mean.

**Comment by anthonyanjorin** [comment]
So now only the deprecated code remains.   This is actually a more general task (i.e., slowly getting completely rid of our evil eMoflon.load* methods).

**Comment by erhanleblebici** [comment]
fixed deprecated code
