### ISSUE TITLE
[TGG] Dev workspace not building due to Consistency Check?

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#487]
With the new consistency check operationalization, the TGG DotToTGGTGG in our dev workspace does not compile anymore.

I assume this is because the compiler does not check if the TGG is only meant to be compiled in e.g. the backward direction.

Please add a new enum value for CONSISTENCY_CHECK and only perform the operationalization if either ALL or CONSISTENCY_CHECK is chosen as TGG build mode!

@erhanleblebici

**Comment by anthonyanjorin** [comment]
Has this been done?

**Comment by Arikae** [comment]
Problem has to be solved by implementing CSP Constraints also for the case where every component is set to bound -> we should generate them and throw new UnsupportedOperationException if it's not implemented
