### ISSUE TITLE
EA Plugin works does sometimes break

### ISSUE THREAD

**Issue by jbuerdek** [eMoflon/emoflon-issue-tracking-system#490]
Sometimes the EA plugin does not load anymore without any reason. Solution is to create a new Windows user and start EA from this user. Roland has a Script to do this. It should be documented somewhere in the Handbook or FAQs.

**Comment by RolandKluge** [comment]
Solution is desribed here: https://github.com/eMoflon/emoflon-issue-tracking-system/wiki/Using-EA-With-A-Second-Windows-Account
