### ISSUE TITLE
[EA] Allow to upgrade eMoflon addin

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#495]
Currently, the EA addin has to be uninstalled manually before installing a new version.

There seems to be an option that allows you to perform upgrades.

Could we also use this in our project to avoid the manual step in between?

See (for example): https://www.add-in-express.com/creating-addins-blog/2014/01/23/wix-installer-upgrade/

**Comment by anthonyanjorin** [comment]
That would be great.  Alex, Sven, and I tried once to do this and it just didn't work.  Was terrible to test - worked fine on some computers, didn't update on others (without any error message).  We finally gave up and preferred the current awkward solution, which is at least deterministic and clear.
Please feel free to make a new attempt, perhaps wix is better than what we had before.
In any case, one must then test carefully (different computer, Windows 8 vs. XP, etc.) to find out if it really works and can be trusted.

**Comment by RolandKluge** [comment]
Ok, seems to work. Tested with multiple versions and also tested that downgrades are being blocked.
