### ISSUE TITLE
Textual Demo Project does not load: MOSLLoadException, Cannot load implicit imports

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#499]
With the current version of eMoflon, the textual demo does not build.

Upon eMoflon building, the following error message appears at the *MOSL* node:

    org.moflon.mosl.utils.exceptions.MoslLoadException: Cannot load implicit Imports

eMoflon version: 1.7.14

@anthonyanjorin

**Comment by SchroedingersCatIsUndead** [comment]
I can't reproduce this exception, but I found and fixed a bug which can produce this exception under certain conditions. I hope this fix will fix your problems.
