### ISSUE TITLE
[TGG] Reduce number of generated stubs

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#500]
At the moment we have Trafo, Sync, ModelGen, ModelGenScalabilityTest and TrafoScalabilityTest

I don't think we need ModelGenScalabilityTest, and it would be nice to integrate the functionality of TrafoScalabilityTest into ModelGen.  5 files are just to many :)

**Comment by erhanleblebici** [comment]
removed scalability test stubs
