### ISSUE TITLE
[TGG] Better error handling when TGG building fails and an NullPointerExeption is thrown

### ISSUE THREAD

**Issue by LarsK01** [eMoflon/emoflon-issue-tracking-system#502]
Better error handling when TGG building fails and an NullPointerExeption is thrown

The error occured for example on chapter 5 of the Handbook, when you run the transformation first.

Errormessage:

0 [main] ERROR org.moflon.tgg.algorithm.synchronization.SynchronizationHelper  - Your TGG DictionaryCodeAdapter is not translation locally complete! This means I was unable to translate the input graph without backtracking.
This is usually due to TGG rules that do not have enough context information in the input component to guarantee the required context in the correspondence and output components when translating.
Please consider your TGG carefully and make sure that all context elements in the output component can be implied from the input context elements of each rule.
I got stuck while trying to extend the following source matches: [NodeToDictionaryRule]
12 [main] WARN org.moflon.tgg.algorithm.synchronization.Synchronizer  - -------------------
I was unable to collect any matches for  the following elements:
Nodes       (0):
Edges       (0):
If this is unexpected, you should perhaps debug the isAppropriate-methods of the rules that are supposed to match to understand what the problem is.
To get rid of this message, you could add rules to explicitly match and ignore these elements.
Note that local-completeness errors might have something to do with these missing matches!

Exception in thread "main" java.lang.NullPointerException
	at org.moflon.tgg.algorithm.synchronization.SynchronizationHelper.saveTrg(SynchronizationHelper.java:533)
	at org.moflon.tie.DictionaryCodeAdapterTrafo.performForward(DictionaryCodeAdapterTrafo.java:46)
	at org.moflon.tie.DictionaryCodeAdapterTrafo.performForward(DictionaryCodeAdapterTrafo.java:61)
	at org.moflon.tie.DictionaryCodeAdapterTrafo.main(DictionaryCodeAdapterTrafo.java:32)

**Comment by anthonyanjorin** [comment]
Could you explain what exactly should be improved?  The error message states clearly enough: "I got stuck while trying to extend the following source matches: [NodeToDictionaryRule]".

Was this not the case?  What exactly was the problem?  Was it a well-defined point in the handbook where one was supposed to try out the tgg?

**Comment by erhanleblebici** [comment]
Apparently, the logger messages have been implemented
