### ISSUE TITLE
[TGG Debug] Target elements of triple matches are not shown appropriately 

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-issue-tracking-system#503]
see the screenshot to see what I'm missing:

![screenshot 2015-07-12 19 48 55](https://cloud.githubusercontent.com/assets/11506522/8639132/a30c5ca0-28d0-11e5-8380-c265af8d8c55.png)

**Comment by mballhausen** [comment]
Instead of the target model stored in the correspondence model, the tempOutputContainer is used as target model. This should fix the empty elements you see.
