### ISSUE TITLE
[TGG EA] Esc does not work after trying to create a link between two nodes 

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#505]
when the dialogue to create a link variable between two object variables has been invoked, it is impossible to cancel this dialogue.  I.e. there is no cancel button and clicking Esc has no effect :(

This is a bit disturbing when e.g., there is either no link at all between the two objects or if one decides not to create a link variable.

**Comment by RolandKluge** [comment]
The "cancel" button was removed during the last hacker days because EA crashed in some situations (see #425). For some reason the issue could only be fixed by removing the "cancel" button. One problem was that we use the **post-**create connector method to open the dialog.

**Comment by anthonyanjorin** [comment]
And how about enabling the ESC button?  Or adding a "none" or "no link" option?

**Comment by RolandKluge** [comment]
We will check this during the next hackerdays.

**Comment by RolandKluge** [comment]
Now, ESC can be used again (there is a Cancel button).
