### ISSUE TITLE
TGG CodeGen problem with boolean flags in attribute constraints

### ISSUE THREAD

**Issue by mabilov** [eMoflon/emoflon-issue-tracking-system#506]
The generation of TGG rules implementation creates code with some compilation errors when there is a boolean attribute constraint in the TGG rule. The affected method is checkAttributes_FWD. The problem is that the CodeGen utility generates code with get[Boolean variable] instead of is[Boolean variable] in the next lines:
if (!([node].get[Boolean variable]() == true)) { //should be [node].is[Boolean variable]() == true
     ruleResult.setSuccess(false);
     return ruleResult;
}

e.g:
if (!(pgw.getDiverging() == true))  should be if (!(pgw.isDiverging() == true))

**Comment by anthonyanjorin** [comment]
this should be fixed now.
