### ISSUE TITLE
[MOSL] SokobanGUI cannot be started

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#520]
After "Click to perform", SokobanGUI appears in the workspace, but cannot be started due to the following error:

Fehler: Hauptklasse org.moflon.tutorial.boardgamegui.Controller konnte nicht gefunden oder geladen werden

I don't know why Eclipse tries to find this class, but the correct class is: *org.moflon.tutorial.sokobangamegui.Controller*

**Comment by anthonyanjorin** [comment]
Thanks Roland!  I always chose the class explicitly and missed this.  Should be fixed now...
