### ISSUE TITLE
New dependencies counteracting the modularization of eMoflon

### ISSUE THREAD

**Issue by gervarro** [eMoflon/emoflon-issue-tracking-system#529]
Sorry, but I am the devil's advocate again...

Introducing new required bundles from the Eclipse UI (org.eclipse.ui.workbench.texteditor, org.eclipse.text, org.eclipse.ui.workbench) in the MoflonIdeCore project counteracts the intended modularization of eMoflon. Please try to remove these newly introduced dependencies.

**Comment by anthonyanjorin** [comment]
Thanks for that...  I was trying to get something to work for the tutorial and it's pretty quick and dirty at the moment.  There is a FIXME there and I'll refactor things once it's working.

**Comment by gervarro** [comment]
OK. No problem. I also recognized that the use of the features from the new dependencies is extremely localized (one method).
