### ISSUE TITLE
Eclipse doesn't propergate changes in plug-in develoment for used Workspaces

### ISSUE THREAD

**Issue by SchroedingersCatIsUndead** [eMoflon/emoflon-issue-tracking-system#530]
Recently I 've changed some things in the plug-in (new Wizards, Wizard order, some markers for MOSL, etc.), but when I started my TestWorkspaces the changes doesn' t exist. But if I create a new Workspace, my changes are been shown. I guess there is something with the ".metadata" from eclipse which saves an old state of the plug-in. 
Can we do something from our side that eclipse doesnot use this annoying behaviour?

**Comment by RolandKluge** [comment]
Do you mean by "TestWorkspace" a runtime workspace (via "Run -> Eclipse Application") or do you deploy eMoflon and test it in a separate Eclipse instance?

If you are using a runtime workspace: Maybe it would help to open the Run Configuration and to select "Clear" in the Main tab. Additionally you could toggle "Clear the configuration area before launching" in the "Configuration" tab.

**Comment by SchroedingersCatIsUndead** [comment]
yes, I mean a runtime workspace. Clear in the main tab clears everything it's like creating a new Workspace, the problem my files are gone.

If I using "Clear the configuration area before launching", it shows no effect perhaps my mentioned guess is wrong.

Is there a way to change the plug-in (i.e. the order of Wizards), where I don't have to setup a new Workspace (or complete clear) to check the changes in the plug-in?

Or I'm the only one who has these problems?

**Comment by SchroedingersCatIsUndead** [comment]
Problem "fixed", the Problem is that I 've switch the Eclipse Version from Luna to Mars and the runtime Workspace configuration is destroyed.
