### ISSUE TITLE
[handbook] Which English should be written in the handbook.

### ISSUE THREAD

**Issue by SchroedingersCatIsUndead** [eMoflon/emoflon-issue-tracking-system#532]
Now when I rework the handbook. I discover that the handbook is sometimes switching between American English and British English. Especially the conjunction of the word "model" is a good Indicator (i.e. modelling is BE, modeling is AE). I think we should decide which English we are using. So we can be more consistent in the handbook. I suggest to write down the decision as comment in the preamble.

**Comment by anthonyanjorin** [comment]
So the decision was actually British + ize, following the spelling preferred by the (Concise) Oxford English Dictionary (language tag en-GB-oed).

Erika (as a Canadian) found that a bit hard to adhere to, hence the few inconsistencies here and there.

**Comment by SchroedingersCatIsUndead** [comment]
Ok. I'm someone who does need spelling tools for writting (like thesaurus and lexicon). So I must configure my tex editor for the right language. It is a little bit annoying when these spelling tools mark every "model" conjunction because it is the "wrong" English.
