### ISSUE TITLE
Release site on our webpage cannot be copy&pasted in Eclipse

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#542]
Please change the release update site from www.moflon.org/fileadmin/download/moflon-ide/eclipse-plugin/release/update-site2/ to http://www.moflon.org/fileadmin/download/moflon-ide/eclipse-plugin/release/update-site2/

Eclipse is not clever enough to add this and so the update site is not copy&pasteable.

**Comment by RolandKluge** [comment]
Solved
