### ISSUE TITLE
[Validation] Validation regularly crashes when validating attributes

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#546]
The validation module in Eclipse regularly crashes when validating Ecore models. 

For instance, the EAP file, which can be found at the following URL causes the following error message.

URL: https://github.com/eMoflon/emoflon-issue-tracking-system/blob/master/issuefiles/issue546__de.tudarmstadt.maki.modeling.ktc.incremental.specification.eap.zip

Error message:
Internal exception occured (probably caused by a bug in the validation module): Pattern matching in node [HandleAttributeVariable] failed. Variables: [patternBody] = org.gervarro.democles.specification.emf.PatternBody@1c591de0, [attribute] = org.gervarro.democles.specification.emf.constraint.emf.emf.Attribute@475b634f, [eAttribute] = org.eclipse.emf.ecore.impl.EAttributeImpl@2d5fe1f8 (eProxyURI: platform:/plugin/de.tudarmstadt.maki.modeling.graphmodel/model/Graphmodel.ecore#//Edge/weight). Please report the bug on https://github.com/eMoflon/emoflon-issue-tracking-system/issues
Pattern matching in node [HandleAttributeVariable] failed. Variables: [patternBody] = org.gervarro.democles.specification.emf.PatternBody@1c591de0, [attribute] = org.gervarro.democles.specification.emf.constraint.emf.emf.Attribute@475b634f, [eAttribute] = org.eclipse.emf.ecore.impl.EAttributeImpl@2d5fe1f8 (eProxyURI: platform:/plugin/de.tudarmstadt.maki.modeling.graphmodel/model/Graphmodel.ecore#//Edge/weight).

**Comment by RolandKluge** [comment]
Update: The problem was that I had an outdated "foreign" metamodel as a dependency (GraphModelInterface in the EAP file).

Still, it would be good if the validation does not crash but produce a sensible error message.

**Comment by gervarro** [comment]
Most probably fixed by commit 320. (The full support (for detecting cross-reference resolution failures) was already there, but a wrong validation status report was returned.)
