### ISSUE TITLE
Clean up workspace by removing MOSL related projects

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#551]
If we finally decide to remove MOSL for the moment, this is what has to be done:

* Move the following projects to Attic:
    * MOSL
    * MOSLCodeAdapter
    * TutorialValidation
    * TutorialValidationRules
    * org.moflon.tutorial

* Afterwards search for *MOSL in the workspace and remove all related packages and classes (commit changes together as "Removed MOSL-related classes" so this can be found easily in the history)

* Check plugin.xmls, especially in org.moflon.ide.ui and org.moflon.ide.core for MOSL related extensions.  Remove and commit as above.

* Update relevant dev PSF

* Update feature description of eMoflon plugin (remove deleted plugins) 

*  Tag Handbook projects and then remove textual sections, part by part

*  Remove tutorial explanation from the website

Anything else?

**Comment by anthonyanjorin** [comment]
@SchroedingersCatIsUndead @erhanleblebici @RolandKluge 

Have I forgotten anything?

**Comment by RolandKluge** [comment]
* We should also remove the imported EA packages inside EAP files.
