### ISSUE TITLE
[Democles]  Deletion does not work

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-issue-tracking-system#553]
The following test fails in Damocles_0, I think because the deletion pattern strangely does nothing:

````
backend.democles.onlineSocialNetwork.TestOnlineSocialNetwork.testMethodCallExpressionForBots
testMethodCallExpressionForBots(backend.democles.onlineSocialNetwork.TestOnlineSocialNetwork)
````

**Comment by anthonyanjorin** [comment]
Other tests in TGG_1 are red (everything to do with deletion).

**Comment by RolandKluge** [comment]
Do you mean that the pattern is empty? Maybe, the template is not loaded properly. Could you check the standard output  by running Eclipse with options "-console -consoleLog" whether it contains StringTemplate error messages?

**Comment by gervarro** [comment]
Let me check the situation. Roland modified the StringTemplate error reporting during the last Hacker Days, then I modified the node deletion templates. Unfortunately, both can seriously influence the bootstrapping process...

**Comment by anthonyanjorin** [comment]
Just an additional comment:  after bootstrapping, our dev workspace still builds if you exclude all TGG (there are exactly 3) projects.  As SDMs (now erroneous due to this bug) are used to map TGGs to SDMs, however, the resulting patterns are rubbish and code generation does not work (ergo, all TGG projects do not compile right now).

**Comment by gervarro** [comment]
I edited the templates. Could you please check whether the new setup works for TGGs?

**Comment by anthonyanjorin** [comment]
Great!  Everything's green :+1:
